scratch-org-def: config/project-scratch-def.json
assign-permset: true
permset-name: lcc
run-apex-tests: false
delete-scratch-org: false
show-scratch-org-url: true
open-path: one/one.app#/n/Basic_Messaging